# Generated by Django 2.0.5 on 2018-05-16 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録時間')),
                ('temperature', models.FloatField(blank=True, verbose_name='気温')),
                ('humidity', models.FloatField(blank=True, verbose_name='湿度')),
            ],
            options={
                'verbose_name': '採取データ',
                'verbose_name_plural': '採取データ',
            },
        ),
    ]
